// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqltypes

type KnotInput struct {
	TrackID  *string `json:"trackId,omitempty"`
	Level    *int    `json:"level,omitempty"`
	Visited  *bool   `json:"visited,omitempty"`
	SourceID *uint   `json:"sourceId,omitempty"`
}

type MapInput struct {
	Title      *string `json:"title,omitempty"`
	Public     bool    `json:"public"`
	FlagshipID *string `json:"flagshipID,omitempty"`
}

type MapsFilter struct {
	Author *uint `json:"author,omitempty"`
}

type Mutation struct {
}

type MutationResult struct {
	Success bool `json:"success"`
	Count   int  `json:"count"`
}

type Query struct {
}

type SpotifyAuthToken struct {
	AccessToken string `json:"accessToken"`
	TokenExpiry string `json:"tokenExpiry"`
}
